### ISSUE TITLE
Cors Problem

### ISSUE THREAD

**Issue by fvsadem** [julieng-dup/geocoder-fr#2]
Hi,

Sometime, i have this error :

Access to fetch at 'https://api-adresse.data.gouv.fr/search/?q=15000' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any idea ?

Thanks

**Comment by julieng-dup** [comment]
Hi !

I think you got this error because you try to fetch https service from http application.
That would be fixed by adding CORS header to the request !?

**Comment by fvsadem** [comment]
Hi,

I have the same issue in my pre-production environnment and it's in https

**Comment by julieng-dup** [comment]
The weird think is request response must contain `access-control-allow-origin: *`.
Maybe there are a limit rate on API ? I've got no documentation about that... 

What response header are you get when error happen ?

**Comment by fvsadem** [comment]
This didn't occure anymore... maybe it was an opendata api issue.
