### ISSUE TITLE
Coordinates instead of X / Y position 

### ISSUE THREAD

**Issue by fvsadem** [julieng-dup/geocoder-fr#3]
Hi,

Is there a possibility to add the result in coordinates instead of X/Y positions ?

Maybe a i could do a pull request ? 

Thanks

**Comment by julieng-dup** [comment]
Hi,

You mean about geocodeBestResult return ?

**Comment by julieng-dup** [comment]
Ok, I get it !
Yes please make a pull request :)

**Comment by fvsadem** [comment]
Hi,
I would like to replace the return of geocodeBestResult by :
``return {long: data.features[0].geometry.coordinates[0], lat: data.features[0].geometry.coordinates[1]}``

But it will break your original behavior.

The problem is that you use the terms long & lat to return X & Y... and that's not correct.

Maybe we could return :
``{x: data.features[0].properties.x, y: data.features[0].properties.y, long: data.features[0].geometry.coordinates[0], lat: data.features[0].geometry.coordinates[1]}``

What do you think ?

**Comment by fvsadem** [comment]
Hi,

I think i will make a fork of your project because it breaks your original behavior.

Maybe you have a better solution ?

Thanks

**Comment by julieng-dup** [comment]
Closed by merging #4
